name: CI/CD Pipeline

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.400'
  PROJECT_PATH: './src/DiskProtectorApp/DiskProtectorApp.csproj'

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: Publish application
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} -c Release -r win-x64 --self-contained false -o ./publish /p:DebugType=None /p:DebugSymbols=false

    - name: Organize files
      shell: pwsh
      run: |
        # Crear estructura de directorios usando comandos de PowerShell
        New-Item -ItemType Directory -Path "./DiskProtectorApp-release" -Force
        New-Item -ItemType Directory -Path "./DiskProtectorApp-release/libs" -Force
        New-Item -ItemType Directory -Path "./DiskProtectorApp-release/locales" -Force
        New-Item -ItemType Directory -Path "./DiskProtectorApp-release/config" -Force
        
        # Copiar el ejecutable principal
        Copy-Item -Path "./publish/DiskProtectorApp.exe" -Destination "./DiskProtectorApp-release/" -Force
        
        # Mover DLLs a la carpeta libs
        Get-ChildItem -Path "./publish" -Filter "*.dll" | ForEach-Object {
            Move-Item -Path $_.FullName -Destination "./DiskProtectorApp-release/libs/" -Force
        }
        
        # Mover recursos localizados (solo en/es)
        if (Test-Path "./publish/en") {
            Move-Item -Path "./publish/en" -Destination "./DiskProtectorApp-release/locales/" -Force
        }
        if (Test-Path "./publish/es") {
            Move-Item -Path "./publish/es" -Destination "./DiskProtectorApp-release/locales/" -Force
        }
        
        # Eliminar recursos alemanes si existen
        if (Test-Path "./publish/de") {
            Remove-Item -Path "./publish/de" -Recurse -Force
        }
        
        # Copiar archivos de configuración
        Get-ChildItem -Path "./publish" -Filter "*.json" | ForEach-Object {
            Move-Item -Path $_.FullName -Destination "./DiskProtectorApp-release/config/" -Force
        }
        Get-ChildItem -Path "./publish" -Filter "*.config" | ForEach-Object {
            Move-Item -Path $_.FullName -Destination "./DiskProtectorApp-release/config/" -Force
        }

    - name: Create compressed archive
      run: |
        tar -czf ./DiskProtectorApp-${{ github.ref_name }}.tar.gz -C ./DiskProtectorApp-release .

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ./DiskProtectorApp-${{ github.ref_name }}.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
